from colorist import BgColor, print_color

if __name__ == "__main__":
    print("")
    print_color("This is GREEN background!", color = None, bgcolor = BgColor.GREEN)
    print("")
    print_color("This is YELLOW background!", color = None, bgcolor = BgColor.YELLOW)
    print("")
    print_color("This is RED background!", color = None, bgcolor = BgColor.RED)
    print("")
    print_color("This is MAGENTA background!", color = None, bgcolor = BgColor.MAGENTA)
    print("")
    print_color("This is BLUE background!", color = None, bgcolor = BgColor.BLUE)
    print("")
    print_color("This is CYAN background!", color = None, bgcolor = BgColor.CYAN)
    print("")
    print_color("This is WHITE background!", color = None, bgcolor = BgColor.WHITE)
    print("")
    print_color("This is BLACK background!", color = None, bgcolor = BgColor.BLACK)
    print("")
