from colorist import bg_green, bg_red, bg_yellow, bg_magenta, bg_blue, bg_cyan, bg_white, bg_black

if __name__ == "__main__":
    print("")
    bg_green("This is GREEN background!")
    print("")
    bg_yellow("This is YELLOW background!")
    print("")
    bg_red("This is RED background!")
    print("")
    bg_magenta("This is MAGENTA background!")
    print("")
    bg_blue("This is BLUE background!")
    print("")
    bg_cyan("This is CYAN background!")
    print("")
    bg_white("This is WHITE background!")
    print("")
    bg_black("This is BLACK background!")
    print("")
