from colorist import green, yellow, red, magenta, blue, cyan, white, black

if __name__ == "__main__":
    print("")
    green("This is GREEN!")
    print("")
    yellow("This is YELLOW!")
    print("")
    red("This is RED!")
    print("")
    magenta("This is MAGENTA!")
    print("")
    blue("This is BLUE!")
    print("")
    cyan("This is CYAN!")
    print("")
    white("This is WHITE!")
    print("")
    black("This is BLACK!")
    print("")
